
lp_core:
    resource: "@LPCoreBundle/Resources/config/routing.yml"
    prefix:   /

lp_partner:
    resource: "@LPPartnerBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: LPUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout