
lp_core:
    resource: "@LPCoreBundle/Resources/config/routing.yml"
    prefix:   /

lp_partner:
    resource: "@LPPartnerBundle/Resources/config/routing.yml"
    prefix:   /

lp_user:
    resource: "@LPUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: LPUserBundle:Security:login }

register:
    pattern:   /register
    defaults:  { _controller: LPUserBundle:Security:register }
    requirements:
        _method:  GET|POST

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
    defaults: { _controller: LPUserBundle:Security:logout }

reset:
    path:     /reset
    defaults: { _controller: LPUserBundle:Security:reset }