# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
            #algorithm:   sha1
            #iterations: 1
            #encode_as_base64: false
        LP\UserBundle\Entity\User: plaintext
            #algorithm:   sha1
            #iterations: 1
            #encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: LP\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
            logout:
                path:   logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/reset$, roles: IS_AUTHENTICATED_ANONYMOUSLY }