services:
#    lp_user.example:
#        class: LP\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    lp_user.mail:
        class: LP\UserBundle\MailService\MailService
        arguments:  [%email_sender%, @mailer, @templating]

    lp_user.reset:
        class: LP\UserBundle\ResetService\ResetService