<?php

namespace LP\PartnerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneCallRepository extends EntityRepository
{
}
